# Setup
title:               CJT Cooks
tagline:             Cooking one step at a time
url:                 http://cjtcooks.github.io
paginate:            6
paginate_path:       "/recipes/page:num/"
baseurl:             "/"
permalink:           /recipes/:title

# About/contact
author:
  name:              CJT
  email:             cjtcooks@gmail.com


# Gems
gems:
  - jekyll-paginate
